### ISSUE TITLE
RangeError on non-id value

### ISSUE THREAD

**Issue by jc00ke** [sporkrb/spork#118]
My specs fine w/o spork. When I run all of my acceptance tests (mix of akephalos & capybara-webkit) I get:

```
Failure/Error: sign_in_as(me)
     RangeError:
       0x000000053621e4 is not id value
     # ./spec/acceptance/support/helpers.rb:5:in `sign_in_as'
     # ./spec/acceptance/activity_box_feature_spec.rb:107:in `block (2 levels) in <top (required)>'
```

When I run this file by itself, I get a bunch of errors, including 0x00... is recycled object,

Not sure how I can help you debug, but please let me know what other info would be helpful.

**Comment by jah2488** [comment]
Hrmm, I'm having the same issue. Atleast I know its spork...

**Comment by jc00ke** [comment]
I'm using spork on my current project and haven't seen any errors like this. I'll leave this open until someone decides otherwise.
