### ISSUE TITLE
undefined method `asset_environment' for class `Sprockets::Railtie' (NameError) 

### ISSUE THREAD

**Issue by dwormuth** [sporkrb/spork#135]
I tried to run Spork with Rails 3.1.0.rc6 and get this error:

undefined method `asset_environment' for class`Sprockets::Railtie' (NameError)
/Users/dwormuth/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc6/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/Users/dwormuth/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc6/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
/Users/dwormuth/.rvm/gems/ruby-1.9.2-p180@rails31/gems/sass-rails-3.1.0.rc.3/lib/sass/rails/monkey_patches.rb:7:in `included'
/Users/dwormuth/.rvm/gems/ruby-1.9.2-p180@rails31/gems/sass-rails-3.1.0.rc.3/lib/sass/rails/monkey_patches.rb:23:in`include'
.......

I do not get this error against Rails 3.1.0.rc5

**Comment by chaffeqa** [comment]
I had the exact same problem, switched to rc5 and it didnt occur.

I will give it a shot in an hr or so
