### ISSUE TITLE
spork and spree

### ISSUE THREAD

**Issue by ezotrank** [sporkrb/spork#145]
I use spork with spree and all be good, but yesterday I install spree_static_content and now when I run test with spork I see this error:

```
  undefined method `hook' for #<#<Class:0x7f09019b69a8>:0x7f0901979648> (ActionView::Template::Error)
  ./vendor/bundler/ruby/1.8/gems/spree_dash-0.60.1/app/views/admin/overview/index.html.erb:3:in `_vendor_bundler_ruby_____gems_spree_dash________app_views_admin_overview_index_html_erb__2003914702_69838328917840_0'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/template.rb:135:in `send'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/template.rb:135:in `render'
  ./vendor/bundler/ruby/1.8/gems/activesupport-3.0.9/lib/active_support/notifications.rb:54:in `instrument'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/template.rb:127:in `render'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/render/rendering.rb:59:in `_render_template'
  ./vendor/bundler/ruby/1.8/gems/activesupport-3.0.9/lib/active_support/notifications.rb:52:in `instrument'
  ./vendor/bundler/ruby/1.8/gems/activesupport-3.0.9/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  ./vendor/bundler/ruby/1.8/gems/activesupport-3.0.9/lib/active_support/notifications.rb:52:in `instrument'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/render/rendering.rb:56:in `_render_template'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_view/render/rendering.rb:26:in `render'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/abstract_controller/rendering.rb:115:in `_render_template'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/abstract_controller/rendering.rb:109:in `render_to_body'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_controller/metal/renderers.rb:47:in `render_to_body'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/abstract_controller/rendering.rb:102:in `render_to_string'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/abstract_controller/rendering.rb:93:in `render'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_controller/metal/rendering.rb:17:in `render'
  ./vendor/bundler/ruby/1.8/gems/actionpack-3.0.9/lib/action_controller/metal/instrumentation.rb:40:in `render'
  ./vendor/bundler/ruby/1.8/gems/activesupport-3.0.9/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /usr/lib64/ruby/1.8/benchmark.rb:308:in `realtime'
```

But when I run test from rake cucumber without --drb all good. I find dirty solution that copy all helper in support/spree_hook.rb file, but it's not good.

**Comment by ezotrank** [comment]
spree static content is not author of this error. For reproduction I change my **app/controller/application_controller.rb**
**class ApplicationController < Spree::BaseController** and now spork can't find spree helpers but cucumber can. But when I create a namespace for example dashboard and create application_controller for this namespace with
**class Dashboard::ApplicationController < Spree::BaseController**
all good

**Comment by ezotrank** [comment]
I think I find not native solution. I create hook https://gist.github.com/1265921 in features/support and this hook load only when  we use spork in dev environment
