### ISSUE TITLE
undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by brandoncordell** [sporkrb/spork#157]
I have the spork 0.9.0.rc9 gem on my machine (OS X 10.7 up to date with all os updates) and in my Gemfile (Rails 3.1.1). When I try to run spork --bootstrap I get the following error:

undefined method 'split' for nil:NilClass (NoMethodError)
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:10:in 'initialize'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:25:in 'new'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:25:in 'block in latest_load_paths'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:24:in 'each'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:24:in 'inject'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/gem_helpers.rb:24:in 'latest_load_paths'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork.rb:108:in 'other_spork_gem_load_paths'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork.rb:101:in 'detect_and_require'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/test_framework.rb:167:in '<top (required)>'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/runner.rb:49:in 'find_test_framework'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/runner.rb:57:in 'run'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/lib/spork/runner.rb:10:in 'run'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/gems/spork-0.9.0.rc9/bin/spork:10:in '<top (required)>'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/bin/spork:19:in 'load'
/Users/brandon/.rvm/gems/ruby-1.9.2-p180/bin/spork:19:in '<main>'

**Comment by macmartine** [comment]
+1

**Comment by macmartine** [comment]
I emptied my rvm gemset and re-ran 'bundle install' and all was good. No idea what caused that.

**Comment by brandoncordell** [comment]
@macmartine thanks man, I created a whole new gemset for my project, ran bundle install and it works like a champ. I'm having an issue with guard-spork, but that's another story.

I would still say this an issue. Maybe a dependency problem causing this to happen. I mean I don't think you'd want to empty your gemset every time you hit this issue in a project.

**Comment by solenko** [comment]
Use 
`bundle exec spork`

**Comment by bhgames** [comment]
bundle exec spork does nothing, solenko.
