### ISSUE TITLE
"NO tuple" when running spork on windows (almost always)

### ISSUE THREAD

**Issue by HyveAG** [sporkrb/spork#199]
I know there's been some issues related to this error, but mine seems to be a little different as I am always experiencing this error, not only after a few minutes.

I run spork rspec, wait until a slave is provided and then run "rspec spec". And the error is:

```
Running tests with args ["spec"]...
- NO tuple
Done.
```

Interestingly, it sometimes, but really really only sometimes, works. And I can't tell you when it does and when it doesn't.

However, I get the following warning when starting spork:

```
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/spork-a07c59d6652d/lib/spork.rb:4: warning: already initialized constant BINARY
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/spork-a07c59d6652d/lib/spork.rb:5: warning: already initialized constant LIBDIR
```

When terminating spork, it throws errors that it can't find processes (sry for the output being in German, it says "ERROR: process XYZ could not be found"):

```
magazine_slave_provider.rb:30:in `join': Interrupt
        from magazine_slave_provider.rb:30:in `<main>'
ring_server.rb:10:in `join': Interrupt
        from ring_server.rb:10:in `<main>'
FEHLER: Der Prozess "4820" wurde nicht gefunden.
FEHLER: Der Prozess "184" wurde nicht gefunden.
FEHLER: Der Prozess "4392" wurde nicht gefunden.
```

I tried `gem "spork"`,  `gem "spork", "~> 1.0rc" and`gem 'spork', :git => 'https://github.com/sporkrb/spork.git'`. None of them resolved the issue.

**Comment by HyveAG** [comment]
New day, new try - today spork works as expected, I don't get the "NO tuple" error. This is really, really strange and I have a hard time debugging where it came from. I tried a reboot when I had the error, too, so I don't think it was due to zombie processes sticking around.
I will update this page when the issue arises again.

**Comment by HyveAG** [comment]
I am sorry to say that I am again encountering the issue. I haven't changed anything though, it's the very same setup. I would love to debug it a little more, if only I had a point to start.

**Comment by sixty4bit** [comment]
I think you just have to sit back and take a breather... and wait. Spork says it is ready and listening but in fact, I think there are still things that have to start up. I think you have to wait until the following message shows up:

--> DRb magazine_slave_service: 1 provided...

At that point everything is ready to go. The bug may need to be reworded to say "Be truthful about when Spork is ready."
