### ISSUE TITLE
Diagnose outputs stack trace when detailing requires

### ISSUE THREAD

**Issue by joallard** [sporkrb/spork#206]
I even suspect it doesn't really list all preloaded files. 

On `spork -d`:

```
- Spork Diagnosis -
-- Summary --
config/application.rb
config/boot.rb
config/initializers/backtrace_silencers.rb
config/initializers/devise.rb
config/initializers/inflections.rb
config/initializers/mime_types.rb
config/initializers/secret_token.rb
config/initializers/session_store.rb
spec/factories.rb
spec/spec_helper.rb



-- Detail --



--- config/application.rb ---



--- config/boot.rb ---



--- config/initializers/backtrace_silencers.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- config/initializers/devise.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- config/initializers/inflections.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- config/initializers/mime_types.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- config/initializers/secret_token.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- config/initializers/session_store.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- spec/factories.rb ---
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/find_definitions.rb:16:in `block in find_definitions'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/factory_girl-3.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/factory_girl_rails-3.5.0/lib/factory_girl_rails/railtie.rb:26:in `block in <class:Railtie>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:34:in `call'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:42:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:30:in `run'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `each'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/application.rb:136:in `initialize!'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/railties-3.2.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `block in require'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:251:in `require'
spec/spec_helper.rb:14:in `block in <top (required)>'
/home/jon/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc3/lib/spork.rb:24:in `prefork'
spec/spec_helper.rb:6:in `<top (required)>'



--- spec/spec_helper.rb ---
```

`spec_helper.rb`:

``` ruby
require 'rubygems'
require 'spork'
#uncomment the following line to use spork with the debugger
#require 'spork/ext/ruby-debug'

Spork.prefork do ### Line 6 ###
  ENV["RAILS_ENV"] ||= 'test'

  # Devise likes to load the User model. We want to avoid this. It 
  # does so in the routes file, when calling devise_for :users, :path 
  # => "my_account". The solution? Delay route loading.
  require 'rails/application'
  Spork.trap_method(Rails::Application::RoutesReloader, :reload!)
  require File.expand_path("../../config/environment", __FILE__) ### Line 14 ###

  require 'rspec/rails'
  require 'rspec/autorun'
  require 'capybara/rails'
  require 'capybara/rspec'

  # Requires supporting ruby files with custom matchers and macros, etc,
  # in spec/support/ and its subdirectories.
  Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}
  binding.pry

  RSpec.configure do |config|

    # ## Mock Framework
    #
    # If you prefer to use mocha, flexmock or RR, uncomment the appropriate line:
    #
    # config.mock_with :mocha
    # config.mock_with :flexmock
    # config.mock_with :rr

    # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
    config.fixture_path = "#{::Rails.root}/spec/fixtures"

    # If you're not using ActiveRecord, or you'd prefer not to run each of your
    # examples within a transaction, remove the following line or assign false
    # instead of true.
    config.use_transactional_fixtures = true

    # If true, the base class of anonymous controllers will be inferred
    # automatically. This will be the default behavior in future versions of
    # rspec-rails.
    config.infer_base_class_for_anonymous_controllers = false

    # Run specs in random order to surface order dependencies. If you find an
    # order dependency and want to debug it, you can fix the order by providing
    # the seed, which is printed after each run.
    #     --seed 1234
    config.order = "random"
  end
end

Spork.each_run do
  # FactoryGirl.reload
end
```

**Comment by imxxb** [comment]
I have the same issue with rails 3.2.7

**Comment by brunocruzcoelho** [comment]
any update on this?
I have the same problem in rails 3.2.12

**Comment by ianrae** [comment]
and for me in 3.2.1.  I'm trying to speedup rspec integration_tests...
