### ISSUE TITLE
Cannot run spork with updated Rails4/RSpec3

### ISSUE THREAD

**Issue by onebree** [sporkrb/spork#261]
guard/guard-spork#134

**GEM VERSIONS**
Rails 4.2.0
ruby 1.9.3p547 (2014-05-14) [x86_64-linux]
rspec-core (3.1.7)
guard (2.11.1)
guard-compat (1.2.0)
guard-spork (2.1.0)
spork (1.0.0rc4)
spork-rails (4.0.0)
spork-testunit (0.0.8)

I have not used RSpec since December, when our app was still Rails 3. Since, we've upgraded to Rails 4 and updated the necessary gems. I have not changed anything in the `Guardfile`, `.rspec`, or `spec/spec_helper.rb` files yet.

When I run `bundle exec guard` like I used to, I receive no error (except for Rails-specific deprecation warnings). When I switch to another tab in my terminal, I run `bundle exec rspec spec/features/admin/login_spec.rb`. I receive the following error/backtrace:

```
Exception encountered: #<NameError: uninitialized constant RSpec::Core::CommandLine>
backtrace:
/usr/local/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc4/lib/spork/test_framework/rspec.rb:11:in `run_tests'
/usr/local/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc4/lib/spork/run_strategy/forking.rb:13:in `block in run'
/home/hstevens/.bundler/ruby/1.9.1/spork-224df492657e/lib/spork/forker.rb:21:in `block in initialize'
/home/hstevens/.bundler/ruby/1.9.1/spork-224df492657e/lib/spork/forker.rb:18:in `fork'
/home/hstevens/.bundler/ruby/1.9.1/spork-224df492657e/lib/spork/forker.rb:18:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc4/lib/spork/run_strategy/forking.rb:9:in `new'
/usr/local/lib/ruby/gems/1.9.1/gems/spork-1.0.0rc4/lib/spork/run_strategy/forking.rb:9:in `run'
/home/hstevens/.bundler/ruby/1.9.1/spork-224df492657e/lib/spork/server.rb:49:in `run'
/usr/local/lib/ruby/1.9.1/drb/drb.rb:1548:in `perform_without_block'
/usr/local/lib/ruby/1.9.1/drb/drb.rb:1508:in `perform'
/usr/local/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
/usr/local/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
/usr/local/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'
```

**Comment by typeoneerror** [comment]
+1

**Comment by jpsneto** [comment]
Try this:

``` ruby
gem 'spork', github: 'sporkrb/spork'
gem 'spork-rails'

```

if not work, try 
https://github.com/manafire/spork/commit/38c79dcedb246daacbadb9f18d09f50cc837de51#diff-937afaa19ccfee172d722a05112a7c6fL6 (this worked for me)

**Comment by onebree** [comment]
Thank you @jpsneto but I decided to use Spring and guard-rspec. Works great.

**Comment by jpsneto** [comment]
Great @onebree
I'm using Windows :\

**Comment by onebree** [comment]
With the extension Windows compat issues, I am glad to use Linux at work, and I use an online VM at home (for personal)

**Comment by bilus** [comment]
Same problem on OS/X.
