### ISSUE TITLE
Diagnoser steps on Bundler's toes

### ISSUE THREAD

**Issue by mcmire** [sporkrb/spork#35]
Found an issue today: Running `spork --diagnose` against an app that loads Bundler on boot (I'm using Padrino here but I imagine the same thing would happen under Rails 3) will die with "private method 'require' called for Bundler:Module". This is because when Spork::Diagnoser overrides Kernel#require, it doesn't mark the new method as private, so Bundler.require ends up getting overridden (or something). Backtrace below:

```
elliot@excalibur:~/code/github/mine/moolah$ ~/code/github/forks/spork/bin/spork --diagnose
Using RSpec
Loading Spork.prefork block...
Booting Padrino...
private method `require' called for Bundler:Module (NoMethodError)
/Users/elliot/code/github/mine/moolah/config/boot.rb:24
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require_without_diagnoser'
/Users/elliot/code/github/forks/spork/lib/spork/diagnoser.rb:31:in `require'
/Users/elliot/code/github/mine/moolah/spec/spec_helper.rb:19
/Users/elliot/code/github/forks/spork/bin/../lib/spork.rb:23:in `prefork'
/Users/elliot/code/github/mine/moolah/spec/spec_helper.rb:14
/Users/elliot/code/github/forks/spork/lib/spork/diagnoser.rb:36:in `load_without_diagnoser'
/Users/elliot/code/github/forks/spork/lib/spork/diagnoser.rb:36:in `load'
/Users/elliot/code/github/forks/spork/lib/spork/test_framework.rb:138:in `preload'
/Users/elliot/code/github/forks/spork/lib/spork/app_framework.rb:61:in `preload'
/Users/elliot/code/github/forks/spork/lib/spork/test_framework.rb:134:in `preload'
/Users/elliot/code/github/forks/spork/bin/../lib/spork.rb:67:in `exec_prefork'
/Users/elliot/code/github/forks/spork/lib/spork/test_framework.rb:120:in `preload'
/Users/elliot/code/github/forks/spork/lib/spork/runner.rb:68:in `run'
/Users/elliot/code/github/forks/spork/lib/spork/runner.rb:9:in `run'
/Users/elliot/code/github/forks/spork/bin/spork:10
```

I fixed it and made a topic branch here: http://github.com/mcmire/spork/tree/diagnoser_bundler_compatibility. Thanks!

**Comment by mcmire** [comment]
Should have said thanks for adding this... so... thanks for adding this ;)

**Comment by timcharper** [comment]
Merged in, thanks :)
