### ISSUE TITLE
spork --help == uninitialized constant Spork::Runner::StringIO (NameError)

### ISSUE THREAD

**Issue by anlek** [sporkrb/spork#38]
When I run spork --help I get:
    Usage: spork [test framework name] [options]

```
Options:
    -b, --bootstrap
    -d, --diagnose
    -h, --help
    -p, --port [PORT]

uninitialized constant Spork::Runner::StringIO (NameError)
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:38:in `supported_test_frameworks_text'
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:32:in `initialize'
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:9:in `new'
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:9:in `run'
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/spork:10
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/bin/spork:19:in `load'
/Users/andrew/.rvm/gems/ree-1.8.7-2010.02/bin/spork:19
```

**Comment by lstoldt** [comment]
I also get this.

**Comment by bdevel** [comment]
I got the same error. I just added require "stringio" to the top of the runner.rb file. Just a quick fix though.

**Comment by jackkinsella** [comment]
I had the same issue when using Rails 3 and Rpec2. 

Bdevel's fix worked. Just type "bundle open spork" on the command prompt, find the runner.rb file, and add require "stringio" to the top of the file.

**Comment by timcharper** [comment]
Fixed by patch provided by Martin Schürrer
