### ISSUE TITLE
hazardous spork drb server crash with mri-1.9.2-p0

### ISSUE THREAD

**Issue by thenrio** [sporkrb/spork#54]
using spork-0.9.0.rc2, server crashed once and complained with following trace

```
/Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/forker.rb:50: [BUG] pthread_mutex_lock: Invalid argument (EINVAL)
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]

-- control frame ----------
c:0012 p:---- s:0045 b:0045 l:000044 d:000044 CFUNC  :raise
c:0011 p:0083 s:0041 b:0041 l:0004e0 d:0004e0 METHOD /Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/forker.rb:50
c:0010 p:0055 s:0037 b:0037 l:001c30 d:001c30 METHOD /Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:17
c:0009 p:0023 s:0031 b:0031 l:000030 d:000030 METHOD /Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/server.rb:47
c:0008 p:0098 s:0025 b:0025 l:000024 d:000024 METHOD /Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558
c:0007 p:0146 s:0021 b:0021 l:000020 d:000020 METHOD /Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518
c:0006 p:0042 s:0017 b:0017 l:001838 d:000016 BLOCK  /Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592
c:0005 p:---- s:0012 b:0012 l:000011 d:000011 FINISH
c:0004 p:---- s:0010 b:0010 l:000009 d:000009 CFUNC  :loop
c:0003 p:0068 s:0007 b:0007 l:001838 d:000006 BLOCK  /Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
/Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'
/Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/Users/thenrio/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/server.rb:47:in `run'
/Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:17:in `run'
/Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/forker.rb:50:in `result'
/Users/thenrio/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/forker.rb:50:in `raise'

-- C level backtrace information -------------------------------------------
0   libruby.1.9.1.dylib                 0x000000010017f9d2 rb_vm_bugreport + 210
1   libruby.1.9.1.dylib                 0x0000000100039d04 report_bug + 372
2   libruby.1.9.1.dylib                 0x0000000100039ec8 rb_bug + 200
3   libruby.1.9.1.dylib                 0x000000010003a4ee rb_bug_errno + 1566
4   libruby.1.9.1.dylib                 0x00000001001854fa thread_raise_m + 186
5   libruby.1.9.1.dylib                 0x0000000100165487 vm_call_method + 983
6   libruby.1.9.1.dylib                 0x0000000100168215 vm_exec_core + 8293
7   libruby.1.9.1.dylib                 0x000000010016fe53 vm_exec + 1507
8   libruby.1.9.1.dylib                 0x000000010017cec1 loop_i + 545
9   libruby.1.9.1.dylib                 0x000000010003ee67 rb_rescue2 + 519
10  libruby.1.9.1.dylib                 0x0000000100161c46 rb_f_loop + 54
11  libruby.1.9.1.dylib                 0x0000000100165487 vm_call_method + 983
12  libruby.1.9.1.dylib                 0x0000000100168215 vm_exec_core + 8293
13  libruby.1.9.1.dylib                 0x000000010016fe53 vm_exec + 1507
14  libruby.1.9.1.dylib                 0x000000010017118a rb_vm_invoke_proc + 842
15  libruby.1.9.1.dylib                 0x0000000100187495 thread_start_func_2 + 1669
16  libruby.1.9.1.dylib                 0x000000010018762d thread_start_func_1 + 29
17  libSystem.B.dylib                   0x00007fff83765456 _pthread_start + 331
18  libSystem.B.dylib                   0x00007fff83765309 thread_start + 13
```
## what was I doing ?

running a controller spec with language errors in
from
    -  rescue_from ActiveRecord::RecordNotFound do |error|
to
    +  rescue_from Errors::DocumentNotFound do |error|
## can I reproduce it ?

I'm afraid not : I started server again, replayed code and server did not wince
## configuration hint ?

```
Spork.each_run do
  ### issues are
  # http://github.com/rspec/rspec-core/issues/62
  # http://github.com/thoughtbot/factory_girl/issues/55
  # 
  Dir["#{Rails.root}/app/**/*.rb"].each { |f| load f }   
end
```

Kill this report if information does not become more precise?
Cheers, Thierry

**Comment by timcharper** [comment]
I am using spork with 1.9.2p0 with lots of success. Closing :)
