### ISSUE TITLE
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- b (LoadError)

### ISSUE THREAD

**Issue by tomoyuki28jp** [sporkrb/spork#64]
I'm not sure if this is a issue of spork, but it only happens when I run rspec via spork. (Not all the time. Sometimes it works fine.)

x300% rspec -drb -c spec/models/user_spec.rb 
<c/models/user_spec.rb 
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- b (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration.rb:162:in `block in requires='
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration.rb:162:in`map'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration.rb:162:in `requires='
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration_options.rb:22:in`block in configure'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration_options.rb:21:in `each'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/configuration_options.rb:21:in`configure'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/command_line.rb:17:in `run'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/runner.rb:55:in`run_in_process'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/runner.rb:46:in `run'
    from /home/tomo/.rvm/gems/ruby-1.9.2-p0/gems/rspec-core-2.0.1/lib/rspec/core/runner.rb:10:in`block in autorun'

ubuntu 10.04
rvm 1.0.20
ruby 1.9.2p0 (2010-08-18 revision 29036) [i686-linux]
Rails 3.0.0
rspec (2.0.1)
rspec-core (2.0.1)
rspec-expectations (2.0.1)
rspec-mocks (2.0.1)
rspec-rails (2.0.1)
spork (0.9.0.rc2)

**Comment by tomoyuki28jp** [comment]
ah, this was my mistake.
s/-drb/--drb/

sorry to bother you!
