### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by petyosi** [sporkrb/spork#70]
Using REE on ubuntu:

<pre>
bundle exec spork
Using RSpec
Preloading Rails environment
Loading Spork.prefork block...
Spork is ready and listening on 8989!
Running tests with args ["--color", "--format", "d", "spec/models/bag_item_spec.rb"]...
Exception encountered: #<SystemStackError: stack level too deep>
backtrace:
/usr/lib/ruby/1.8/drb/drb.rb:1087:in `method_missing'
/usr/lib/ruby/1.8/drb/drb.rb:1105:in `with_friend'
/usr/lib/ruby/1.8/drb/drb.rb:1086:in `method_missing'
/usr/lib/ruby/1.8/drb/drb.rb:1074:in `respond_to?'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/forking.rb:10:in `run'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/magazine/../../../spork/forker.rb:21:in `initialize'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/magazine/../../../spork/forker.rb:18:in `fork'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/magazine/../../../spork/forker.rb:18:in `initialize'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/forking.rb:9:in `new'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/run_strategy/forking.rb:9:in `run'
/home/petyo/.bundler/ruby/1.8/spork-63761d5cb9e0/lib/spork/server.rb:48:in `run'
/usr/lib/ruby/1.8/drb/drb.rb:1558:in `__send__'
/usr/lib/ruby/1.8/drb/drb.rb:1558:in `perform_without_block'
/usr/lib/ruby/1.8/drb/drb.rb:1518:in `perform'
/usr/lib/ruby/1.8/drb/drb.rb:1592:in `main_loop'
/usr/lib/ruby/1.8/drb/drb.rb:1588:in `loop'
/usr/lib/ruby/1.8/drb/drb.rb:1588:in `main_loop'
/usr/lib/ruby/1.8/drb/drb.rb:1584:in `start'
/usr/lib/ruby/1.8/drb/drb.rb:1584
</pre>

**Comment by timcharper** [comment]
I can't reproduce this... more details required

**Comment by petyosi** [comment]
OS is Ubuntu 10.04 server (64 bit). 
ruby enterprise is installed using Brightbox packages:
http://wiki.brightbox.co.uk/docs:ruby-enterprise

Let me know if you need any other details. I can prepare a vagrant setup which reproduces the problem.

**Comment by gkop** [comment]
I replicated this on my CI server but not on my dev box (where everything works perfect with or without the spork servers running):

Ubuntu Server 10.10 x86_64
[Gemfile.lock](http://pastie.org/2089153)
tried Spork 0.8.5 and 0.9.0.rc8
no spork servers running, but spork set up in rspec and cucumber

The bug surfaced any time an ActiveResource call was made during the tests.

**Comment by snitko** [comment]
Confirmed: ubuntu, rvm with ruby 1.9.3 and Rails 3.2.13
