### ISSUE TITLE
Using class with Struct creates TypeError (in Rails3)

### ISSUE THREAD

**Issue by wxmn** [sporkrb/spork#77]
This causes error:
class MatchedTweetJob < Struct.new(:tweet_id)
  def perform
  end
end

This does not:
class MatchedTweetJob
  def perform
  end
end

Full trace:

Using RSpec
Loading Spork.prefork block...
superclass mismatch for class MatchedTweetJob (TypeError)
/Users/wxmn/a/muckrack/app/jobs/matched_tweet_job.rb:1
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in `load'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in`load_file'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:453:in`load_file'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:340:in `require_or_load'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:300:in`depend_on'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:216:in `require_dependency'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/engine.rb:138:in`eager_load!'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/engine.rb:137:in `each'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/engine.rb:137:in`eager_load!'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/engine.rb:135:in `each'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/engine.rb:135:in`eager_load!'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/application.rb:108:in `eager_load!'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/application/finisher.rb:41
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`instance_exec'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/initializable.rb:50:in`run_initializers'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`run_initializers'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
/Users/wxmn/a/muckrack/spec/../config/environment.rb:7
/Users/wxmn/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/Users/wxmn/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/Users/wxmn/a/muckrack/spec/spec_helper.rb:13
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork.rb:23:in`prefork'
/Users/wxmn/a/muckrack/spec/spec_helper.rb:7
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/test_framework.rb:138:in `load'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/test_framework.rb:138:in`preload'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/app_framework.rb:64:in `preload'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/test_framework.rb:134:in`preload'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork.rb:67:in `exec_prefork'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/test_framework.rb:120:in`preload'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:25:in `preload'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:74:in`run'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/../lib/spork/runner.rb:9:in `run'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/gems/spork-0.8.4/bin/spork:10
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/bin/spork:19:in`load'
/Users/wxmn/.rvm/gems/ree-1.8.7-2010.02/bin/spork:19

**Comment by ludicast** [comment]
I'm getting the same error with structs (also using delayed job here too :)).

**Comment by liveh2o** [comment]
Same here. Worked fine on Rails 2.3, but throws the same error in Rails 3.

**Comment by humbroll** [comment]
any solution?? have same problem now. :(

**Comment by markiz** [comment]
This error means that you require the same file twice.
Struct.new returns new class every time it's invoked, so the first time you require your file you get one struct, and next time the other.

How you can try to mitigate this:

```
Something = Struct.new(:prop) unless defined?(Something)
class Something
    ...
end
```

or

```
Something = Struct.new(:prop) do 
    ...
end unless defined?(Something)
```

there are some quirks with autoloading though.

**Comment by markiz** [comment]
I ended up not using Structs at all btw.

**Comment by humbroll** [comment]
I got it.
From now on i will not use Struct.new, just use attr_accessor. 
thanks.
