### ISSUE TITLE
Windows: `spork cuc` and `spork rspec` bind to the same port

### ISSUE THREAD

**Issue by dalton** [sporkrb/spork#87]
Just set up spork on Windows and it worked like a charm for Cucumber, but when I tried to run spork rspec concurrently, I received the following message:

> /Ruby192/lib/ruby/1.9.1/rinda/ring.rb:35:in 'bind': Only one usage of each socket address (protocol/network address/port) is normally permitted. - bind(2) (Errno::EADDRINUSE)
>     from /Ruby192/lib/ruby/1.9.1/rinda/ring.rb:35:in `initialize'
>     from ring_server.rb:7:in`new'
>     from ring_server.rb:7:in `<main>'

**Comment by timcharper** [comment]
This didn't always used to be… I wonder when it changed :S

You can specify a port to use when launching Spork, at least for Rspec.

See the last example here:

https://github.com/timcharper/spork/blob/master/features/rspec_rails_integration.feature
